/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WorkerClass */

#ifndef _Included_WorkerClass
#define _Included_WorkerClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WorkerClass
 * Method:    doSomething
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_WorkerClass_doSomething
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
